name: Build Docker Images

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest

    env:
      NODE_IMAGE_VERSION: "23-alpine3.20"

    steps:
      # Check out the repository code
      - name: Check out repository
        uses: actions/checkout@v2

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      # Cache Docker layers to speed up subsequent builds
      - name: Cache Docker layers
        uses: actions/cache@v2.1.4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}-${{ env.FOUNDRY_POINT_VERSION }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Log in to GitHub Container Registry (only for pushes, not PRs)
      - name: Log in to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      # Generate metadata for Docker image, including tags
      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/teriyakidactyl/docker-foundryvtt-server
          tags: |
            ${{ env.NODE_IMAGE_VERSION }}
            latest            
          labels: |
            org.opencontainers.image.title=Foundry VTT Server
            org.opencontainers.image.description=Docker image for Foundry VTT server
            org.opencontainers.image.vendor=TeriyakiDactyl
            org.opencontainers.image.version=${{ github.ref_name }}
            org.opencontainers.image.created=${{ steps.prep.outputs.build_date }}
            org.opencontainers.image.revision=${{ github.sha }}
            com.example.git.branch=${{ github.ref_name }}

      # Prepare additional build arguments
      - name: Prepare build arguments
        id: prep
        run: |
          echo "build_date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT

      # Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            SOURCE_COMMIT=${{ github.sha }}
            BUILD_DATE=${{ steps.prep.outputs.build_date }}
            BRANCH_NAME=${{ github.ref_name }}
            FOUNDRY_VERSION=${{ env.NODE_IMAGE_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64
